def make_journeyoptions_header(OptionsDefinitions, now, path = '.'):
    with open(path + "/journeyoptions.h","w") as file:

        file.write('//header file for journeyoptions class\n')
        file.write('//auto-generated by make_EMTG_missionoptions_journeyoptions.py\n')
        file.write('\n')

        file.write('#pragma once\n')
        file.write('\n')
        file.write('#include "EMTG_enums.h"\n')
        file.write('#include "file_utilities.h"\n')
        file.write('\n')
        file.write('#include <vector>\n')
        file.write('#include <string>\n')
        file.write('#include <iostream>\n')
        file.write('\n')
        file.write('namespace EMTG\n')
        file.write('{\n')
        file.write('    class JourneyOptions\n')
        file.write('    {\n')
    
        file.write('    public:\n')
        file.write('        //constructor - just initializes everything\n')
        file.write('        JourneyOptions();\n')
        file.write('        JourneyOptions(std::string optionsfilename);\n')
        file.write('        JourneyOptions(std::ifstream& optionsFileStream, size_t& lineNumber);\n')
        file.write('        \n')
        file.write('        //destructor\n')
        file.write('        ~JourneyOptions(){};\n')
        file.write('        \n')
        file.write('        //parser\n')
        file.write('        void parse_journey(std::ifstream& optionsFileStream, size_t& lineNumber);\n')
        file.write('        void parse_line(const std::string& linestring, size_t& lineNumber, std::ifstream& optionsFileStream);\n')
        file.write('        \n')
        file.write('        //writer\n')
        file.write('        void write(const std::string& optionsFileName, const bool& newFile = true, const bool& writeAll = true);\n')  
        file.write('        \n')

        file.write('        //fields\n')
        file.write('        size_t number_of_phases;//how many phases in this journey?\n')
        file.write('        double maximum_mass;\n')

        for option in OptionsDefinitions:
            file.write('        ' + option['dataType'] + ' ' + option['name'] + ';//' + option['comment'] + '\n')

        file.write('        \n')                        
        file.write('        //Constraints\n')
        file.write('        std::vector<std::string> ManeuverConstraintDefinitions;\n')
        file.write('        std::vector<std::string> BoundaryConstraintDefinitions;\n')
        file.write('        std::vector<std::string> PhaseDistanceConstraintDefinitions;\n')
        file.write('        \n')
        file.write('        //Decision vector\n')
        file.write('        std::vector< std::tuple<std::string, double> > trialX;\n')
        file.write('        \n')

        file.write('    private:\n')
        file.write('        //lower and upper bounds\n')
        for option in OptionsDefinitions:
            if 'std::string' not in option['dataType'] and 'bool' not in option['dataType']:
                if '[' in str(option['upperBound']) and ']' in str(option['upperBound']):#is this a string containing a list
                        file.write('        ' + option['dataType'] + ' ' + option['name'] + '_lowerBound;\n')
                        file.write('        ' + option['dataType'] + ' ' + option['name'] + '_upperBound;\n')
                else:
                        file.write('        ' + option['dataType'].replace('std::vector<','').replace('>','') + ' ' + option['name'] + '_lowerBound;\n')
                        file.write('        ' + option['dataType'].replace('std::vector<','').replace('>','') + ' ' + option['name'] + '_upperBound;\n')
        
        file.write('        \n')
        file.write('    }; //end class journeyoptions\n')
        file.write('\n')
        file.write('}//close namespace EMTG\n')
